### ISSUE TITLE
[Feature] User can decide to "learn" or not. 

### ISSUE THREAD

**Issue by Jgmedina95** [ur-whitelab/md-agent#68]
It seems like some tools may be reloaded at every create tool cycle, rather than once per mdagent.run call. marking this as an issue for visibility

**Comment by qcampbel** [comment]
whether one of you capture it, can you post the prompt and agent conversation/output here? so I have an idea of how/where the bug occurs

I only wrote the initialization code inside mdagent.run, so I'm surprised this happens

**Comment by Jgmedina95** [comment]
I was wondering that maybe we can try to make it better locally, rather than just skip it for now? Feels a little overkill to make the PR just to skip the tool. (I comment out the tools I dislike for example) although this is just my opinion

**Comment by qcampbel** [comment]
Following up with this issue: after talking with you guys, it seems like this is more about curriculum issue rather than reloading tools. My understanding of the issue is, WorkflowPlan lists an entire workflow plan during the middle of prompt cycle, causing mdagent to retry and repeat steps (i.e. download PDB files, clean it again, etc) from the beginning. Is that correct, @Jgmedina95?
